server:
 port: 8081
propsdemo:
 model:
  first: "Robert"
  second: "George"
 myapp:
  myArrayProps:
   - UK
   - US
   - AU
 cloudplatforms:
  providers:
   - provider: AWS
     company: Amazon
   - provider: GCP
     company: Google
   - provider: Azure
     company: Microsoft
buffer:
 bufferTimes:
  - type: "displayTime"
    batchSize: 5
    timeWindowDuration: "PT5M"
    memoryInUseFlushThresholdPercentage: 30
    awsS3CheckConnectivity: true
  - type: "sharadTime"
    batchSize: 5
    timeWindowDuration: "PT5M"
    memoryInUseFlushThresholdPercentage: 30
    awsS3CheckConnectivity: true


